'use client';
import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
type Brand={id:string;name:string;slug:string;logo_url:string|null;is_active:boolean};
function slugify(value:string){return value.toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
export default function BrandManager(){const [items,setItems]=useState<Brand[]>([]);const [editing,setEditing]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [form,setForm]=useState({name:'',slug:'',logo_url:'',is_active:true});
async function load(){const {data,error}=await supabase.from('brands').select('id,name,slug,logo_url,is_active').order('name');if(error)setMessage(error.message);else setItems((data??[]) as Brand[])} useEffect(()=>{load()},[]);
function reset(){setEditing(null);setForm({name:'',slug:'',logo_url:'',is_active:true});setMessage('')}
function edit(x:Brand){setEditing(x.id);setForm({name:x.name,slug:x.slug,logo_url:x.logo_url??'',is_active:x.is_active});window.scrollTo({top:0,behavior:'smooth'})}
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const payload={name:form.name.trim(),slug:form.slug.trim()||slugify(form.name),logo_url:form.logo_url.trim()||null,is_active:form.is_active};const {error}=editing?await supabase.from('brands').update(payload).eq('id',editing):await supabase.from('brands').insert(payload);if(error)throw error;reset();await load();setMessage(editing?'Marka güncellendi.':'Marka eklendi.')}catch(err){setMessage('Hata: '+(err instanceof Error?err.message:String(err)))}finally{setBusy(false)}}
async function remove(x:Brand){if(!confirm(`${x.name} markası silinsin mi?`))return;setBusy(true);try{const {error}=await supabase.from('brands').delete().eq('id',x.id);if(error)throw error;await load();setMessage('Marka silindi.')}catch(err){setMessage('Silinemedi: '+(err instanceof Error?err.message:String(err)))}finally{setBusy(false)}}
return <><div className="page-head"><div><h1>Markalar</h1><p className="muted">Marka ekleyin, düzenleyin ve görünürlük durumunu yönetin.</p></div></div><form className="form-card" onSubmit={submit}><h2>{editing?'Markayı Düzenle':'Yeni Marka'}</h2><div className="form-grid two"><label>Marka Adı<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:editing?form.slug:slugify(e.target.value)})}/></label><label>Slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Logo URL<input value={form.logo_url} onChange={e=>setForm({...form,logo_url:e.target.value})}/></label></div><label className="check"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Aktif</label><div className="form-actions"><button className="button" disabled={busy}>{busy?'Kaydediliyor…':editing?'Güncelle':'Marka Ekle'}</button>{editing&&<button className="button secondary" type="button" onClick={reset}>Vazgeç</button>}</div></form>{message&&<div className={message.startsWith('Hata')||message.startsWith('Silinemedi')?'error':'ok'}>{message}</div>}<table className="table"><thead><tr><th>Marka</th><th>Slug</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.slug}</td><td>{x.is_active?'Aktif':'Pasif'}</td><td><button className="link-button" onClick={()=>edit(x)}>Düzenle</button> <button className="danger-link" onClick={()=>remove(x)}>Sil</button></td></tr>)}</tbody></table></>}
