'use client';
import { useEffect,useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import { StoreHeader } from '@/components/StoreHeader';
import { AccountGate } from '@/components/AccountGate';
import { AccountNav } from '@/components/AccountNav';
const money=(v:number)=>Number(v).toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
const labels:Record<string,string>={new:'Yeni',confirmed:'Onaylandı',preparing:'Hazırlanıyor',shipped:'Kargolandı',delivered:'Teslim Edildi',cancelled:'İptal Edildi'};
export default function MyOrderDetail(){const{id}=useParams<{id:string}>();const[order,setOrder]=useState<any>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{(async()=>{const{data,error}=await supabase.from('orders').select('id,order_number,status,payment_status,subtotal,shipping_amount,discount_amount,total_amount,created_at,shipping_carrier,tracking_number,tracking_url,shipped_at,addresses(full_name,phone,city,district,address_line,postal_code),order_items(id,product_name,sku,quantity,unit_price,line_total)').eq('id',id).maybeSingle();if(error)setError(error.message);else setOrder(data);setLoading(false)})();},[id]);return <AccountGate><main className="store"><StoreHeader/><section className="account-shell"><AccountNav/><div className="account-main"><Link className="back-link" href="/account/orders">← Siparişlerime dön</Link>{loading?<div className="form-card">Yükleniyor…</div>:!order?<div className="error">{error||'Sipariş bulunamadı veya bu siparişi görüntüleme yetkiniz yok.'}</div>:<><div className="section-head"><div><h1>{order.order_number}</h1><p className="muted">{new Date(order.created_at).toLocaleString('tr-TR')}</p></div><span className={`order-status ${order.status}`}>{labels[order.status]||order.status}</span></div><div className="account-two-col"><div className="form-card"><h2>Ürünler</h2><div className="account-order-items">{order.order_items?.map((i:any)=><div key={i.id} className="account-order-item"><div><b>{i.product_name}</b><small>{i.sku||'SKU yok'} · {i.quantity} adet</small></div><strong>{money(i.line_total)}</strong></div>)}</div></div><div className="form-card"><h2>Teslimat</h2><p><b>{order.addresses?.full_name||'—'}</b></p><p>{order.addresses?.address_line}<br/>{order.addresses?.district} / {order.addresses?.city}<br/>{order.addresses?.phone||''}</p><hr/><div className="summary-row"><span>Ara Toplam</span><b>{money(order.subtotal)}</b></div><div className="summary-row"><span>Kargo</span><b>{money(order.shipping_amount)}</b></div><div className="summary-row"><span>İndirim</span><b>-{money(order.discount_amount)}</b></div><div className="summary-row total"><span>Toplam</span><b>{money(order.total_amount)}</b></div><small className="muted">Ödeme durumu: {order.payment_status}</small></div></div>{(order.shipping_carrier||order.tracking_number)&&<div className="form-card" style={{marginTop:20}}><h2>Kargo Takibi</h2><div className="shipping-track-grid"><div><small>Kargo Firması</small><b>{order.shipping_carrier||'—'}</b></div><div><small>Takip Numarası</small><b>{order.tracking_number||'—'}</b></div><div><small>Kargoya Veriliş</small><b>{order.shipped_at?new Date(order.shipped_at).toLocaleString('tr-TR'):'—'}</b></div></div>{order.tracking_url&&<a className="button" href={order.tracking_url} target="_blank" rel="noreferrer">Kargoyu Takip Et</a>}</div>}</>}</div></section></main></AccountGate>}
