'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { StoreHeader } from '@/components/StoreHeader';
import { useCart } from '@/components/CartProvider';
import { CouponBox } from '@/components/CouponBox';
import { supabase } from '@/lib/supabase';
const money=(v:number)=>v.toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
type Address={id:string;title:string|null;full_name:string;phone:string|null;city:string;district:string;address_line:string;postal_code:string|null;is_default:boolean};
export default function CheckoutPage(){
 const {items,coupon,discount,total,clearCart}=useCart(); const [user,setUser]=useState<any>(undefined); const [customerId,setCustomerId]=useState(''); const [addresses,setAddresses]=useState<Address[]>([]); const [selectedAddress,setSelectedAddress]=useState(''); const [addressMode,setAddressMode]=useState<'saved'|'new'>('new'); const [busy,setBusy]=useState(false); const [result,setResult]=useState<{order?:string,error?:string}>({});
 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getUser();setUser(data.user);if(!data.user)return;const {data:customer}=await supabase.from('customers').select('id').eq('auth_user_id',data.user.id).single();if(!customer)return;setCustomerId(customer.id);const {data:list}=await supabase.from('addresses').select('id,title,full_name,phone,city,district,address_line,postal_code,is_default').eq('customer_id',customer.id).order('is_default',{ascending:false}).order('created_at',{ascending:false});const rows=(list||[]) as Address[];setAddresses(rows);if(rows.length){const preferred=rows.find(a=>a.is_default)||rows[0];setSelectedAddress(preferred.id);setAddressMode('saved')}})()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user||!items.length||!customerId)return;setBusy(true);setResult({});let addressId=selectedAddress;
  if(addressMode==='saved'){if(!addressId||!addresses.some(a=>a.id===addressId)){setResult({error:'Lütfen bir teslimat adresi seçin.'});setBusy(false);return;}}
  else {const fd=new FormData(e.currentTarget);const {data:address,error:aErr}=await supabase.from('addresses').insert({customer_id:customerId,title:String(fd.get('title')||'Teslimat'),full_name:String(fd.get('full_name')),phone:String(fd.get('phone')),city:String(fd.get('city')),district:String(fd.get('district')),address_line:String(fd.get('address')),postal_code:String(fd.get('postal_code')||'')||null,is_default:addresses.length===0}).select('id').single();if(aErr||!address){setResult({error:aErr?.message||'Adres kaydedilemedi.'});setBusy(false);return;}addressId=address.id;}
  const orderNumber=`WEB-${Date.now()}`; const payload=items.map(x=>({product_id:x.id,quantity:x.quantity}));
  const {error:oErr}=await supabase.rpc('create_customer_order_with_stock_v2',{p_order_number:orderNumber,p_shipping_address_id:addressId,p_items:payload,p_notes:null,p_coupon_code:coupon?.code||null});
  if(oErr){setResult({error:oErr.message});setBusy(false);return;}clearCart();setResult({order:orderNumber});setBusy(false);
 }
 if(user===undefined)return <main className="store"><StoreHeader/><section className="checkout-page"><p>Oturum kontrol ediliyor…</p></section></main>;
 return <main className="store"><StoreHeader/><section className="checkout-page"><div className="section-head"><div><h1>Siparişi Tamamla</h1><p className="muted">Teslimat adresinizi seçin ve siparişinizi oluşturun.</p></div><Link href="/cart">← Sepete dön</Link></div>
 {!user?<div className="empty-cart"><h2>Sipariş için giriş yapmalısınız.</h2><p>Üye olduktan sonra sepetiniz korunur.</p><Link className="button" href="/account">Giriş Yap / Üye Ol</Link></div>:
 result.order?<div className="checkout-success"><h2>Siparişiniz alındı ✓</h2><p>Sipariş numarası: <strong>{result.order}</strong></p><p>Stok işlemi siparişle aynı veritabanı işlemi içinde tamamlandı.</p><Link className="button" href="/account/orders">Siparişlerimi Gör</Link></div>:
 !items.length?<div className="empty-cart"><h2>Sepetiniz boş.</h2><Link className="button" href="/products">Ürünleri İncele</Link></div>:
 <form className="checkout-layout" onSubmit={submit}><div className="checkout-form"><div className="form-card"><h2>Teslimat Adresi</h2>{addresses.length>0&&<><div className="form-actions"><button type="button" className={addressMode==='saved'?'button':'button secondary'} onClick={()=>setAddressMode('saved')}>Kayıtlı Adreslerim</button><button type="button" className={addressMode==='new'?'button':'button secondary'} onClick={()=>setAddressMode('new')}>Yeni Adres</button></div>{addressMode==='saved'&&<div className="address-list">{addresses.map(a=><label className="address-card" key={a.id}><input type="radio" name="saved_address" value={a.id} checked={selectedAddress===a.id} onChange={()=>setSelectedAddress(a.id)}/><div><div className="address-title"><b>{a.title||'Adres'}</b>{a.is_default&&<span className="badge active">Varsayılan</span>}</div><p><b>{a.full_name}</b><br/>{a.address_line}<br/>{a.district} / {a.city}{a.phone?<><br/>{a.phone}</>:null}</p></div></label>)}</div>}</>}{(addressMode==='new'||!addresses.length)&&<><label>Adres Başlığı<input name="title" placeholder="Ev / İş"/></label><div className="form-grid two"><label>Ad Soyad<input required={addressMode==='new'} name="full_name"/></label><label>Telefon<input required={addressMode==='new'} name="phone" inputMode="tel"/></label></div><div className="form-grid two"><label>Şehir<input required={addressMode==='new'} name="city"/></label><label>İlçe<input required={addressMode==='new'} name="district"/></label></div><label>Adres<textarea required={addressMode==='new'} name="address" rows={4}/></label><label>Posta Kodu<input name="postal_code"/></label></>}{result.error&&<div className="error">{result.error}</div>}</div></div><aside className="cart-summary"><h2>Sipariş Özeti</h2>{items.map(item=><div key={item.id}><span>{item.name} × {item.quantity}</span><strong>{money(item.price*item.quantity)}</strong></div>)}<CouponBox/>{discount>0&&<div><span>Kupon indirimi</span><strong>−{money(discount)}</strong></div>}<hr/><div className="summary-total"><span>Toplam</span><strong>{money(total)}</strong></div><button disabled={busy} className="button" type="submit">{busy?'Sipariş oluşturuluyor…':'Siparişi Oluştur'}</button><small>Ödeme entegrasyonu henüz aktif değildir; ödeme durumu beklemede oluşturulur.</small></aside></form>}
 </section></main>
}
