'use client';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { supabase } from '@/lib/supabase';
const money=(v:number)=>Number(v||0).toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
const statusLabels:Record<string,string>={new:'Yeni',confirmed:'Onaylandı',preparing:'Hazırlanıyor',shipped:'Kargolandı',delivered:'Teslim Edildi',cancelled:'İptal Edildi'};
const paymentLabels:Record<string,string>={pending:'Bekliyor',paid:'Ödendi',failed:'Başarısız',refunded:'İade Edildi',cancelled:'İptal Edildi'};
const nextStatuses:Record<string,string[]>={new:['confirmed','preparing','cancelled'],confirmed:['preparing','cancelled'],preparing:['shipped','cancelled'],shipped:['delivered'],delivered:[],cancelled:[]};
function validTrackingUrl(value:string){if(!value)return true;try{const url=new URL(value);return url.protocol==='https:'||url.protocol==='http:'}catch{return false}}
type Customer={first_name:string|null;last_name:string|null;email:string|null;phone:string|null};
type OrderItem={id:string;product_name:string;sku:string|null;quantity:number;unit_price:number;line_total:number};
type DeliverySnapshot={full_name?:string|null;address_line?:string|null;district?:string|null;city?:string|null};
type AdminOrder={id:string;order_number:string;status:string;payment_status:string;total_amount:number;shipping_carrier:string|null;tracking_number:string|null;tracking_url:string|null;shipped_at:string|null;shipping_address_snapshot:DeliverySnapshot|null;customers:Customer[];order_items:OrderItem[]};
export default function OrderDetail(){
 const {id}=useParams<{id:string}>(); const [order,setOrder]=useState<AdminOrder|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
 const [shipping,setShipping]=useState({shipping_carrier:'',tracking_number:'',tracking_url:''});
 const load=useCallback(async()=>{setLoading(true);setError('');try{const {data,error}=await supabase.from('orders').select('id,order_number,status,payment_status,total_amount,shipping_carrier,tracking_number,tracking_url,shipped_at,shipping_address_snapshot,customers(first_name,last_name,email,phone),order_items(id,product_name,sku,quantity,unit_price,line_total)').eq('id',id).maybeSingle();if(error){setError('Sipariş bilgileri yüklenemedi. Lütfen tekrar deneyin.');setOrder(null)}else if(!data){setError('Sipariş bulunamadı.');setOrder(null)}else{const typed=data as AdminOrder;setOrder(typed);setShipping({shipping_carrier:typed.shipping_carrier||'',tracking_number:typed.tracking_number||'',tracking_url:typed.tracking_url||''})}}catch{setError('Sipariş yüklenirken beklenmeyen bir hata oluştu.');setOrder(null)}finally{setLoading(false)}},[id]);
 useEffect(()=>{load()},[load]);
 const updateStatus=async(status:string)=>{if(status===order?.status)return;if(status==='cancelled'&&order?.payment_status==='paid'){setError('Ödemesi tamamlanmış sipariş doğrudan iptal edilemez. Önce ödeme iadesini tamamlayın.');return}if(status==='cancelled'&&!confirm('Sipariş iptal edilsin ve ürünler stoğa geri eklensin mi?'))return;setSaving(true);setError('');try{const {error}=await supabase.rpc('admin_update_order_status',{p_order_id:id,p_new_status:status});if(error)setError('Sipariş durumu güncellenemedi. Durum geçişini ve ödeme durumunu tekrar kontrol edin.');else await load()}catch{setError('Sipariş durumu güncellenirken beklenmeyen bir hata oluştu.')}finally{setSaving(false)}};
 const saveShipping=async()=>{if(!order)return;const trackingUrl=shipping.tracking_url.trim();if(!validTrackingUrl(trackingUrl)){setError('Takip bağlantısı http:// veya https:// ile başlayan geçerli bir adres olmalıdır.');return}setSaving(true);setError('');try{const payload={shipping_carrier:shipping.shipping_carrier.trim()||null,tracking_number:shipping.tracking_number.trim()||null,tracking_url:trackingUrl||null,shipped_at:order.status==='shipped'?(order.shipped_at||new Date().toISOString()):order.shipped_at};const {error}=await supabase.from('orders').update(payload).eq('id',id);if(error)setError('Kargo bilgileri kaydedilemedi. Lütfen tekrar deneyin.');else await load()}catch{setError('Kargo bilgileri kaydedilirken beklenmeyen bir hata oluştu.')}finally{setSaving(false)}};
 if(loading)return <p>Yükleniyor…</p>; if(!order)return <div className="error">{error||'Sipariş bulunamadı.'}</div>;
 const allowed=(nextStatuses[order.status]||[]).filter(status=>!(status==='cancelled'&&order.payment_status==='paid')); const delivery=order.shipping_address_snapshot||{}; const customer=order.customers?.[0]||null;
 return <><div className="section-head"><div><h1>{order.order_number}</h1><p className="muted">Sipariş detayı ve operasyon yönetimi</p></div><select disabled={saving||allowed.length===0} value={order.status} onChange={e=>updateStatus(e.target.value)}><option value={order.status}>{statusLabels[order.status]||order.status}</option>{allowed.map(v=><option key={v} value={v}>{statusLabels[v]||v}</option>)}</select></div>{error&&<div className="error">{error}</div>}
 <div className="stats"><div className="card"><b>Müşteri</b><p>{customer?`${customer.first_name||''} ${customer.last_name||''}`.trim()||'—':'—'}</p><small>{customer?.email||''}<br/>{customer?.phone||''}</small></div><div className="card"><b>Teslimat Adresi</b><p>{delivery.full_name||'—'}</p><small>{[delivery.address_line,delivery.district,delivery.city].filter(Boolean).join(' / ')||'—'}</small></div><div className="card"><b>Toplam</b><p>{money(order.total_amount)}</p><small>Ödeme: {paymentLabels[order.payment_status]||order.payment_status||'—'}</small></div></div>
 {order.payment_status==='paid'&&['new','confirmed','preparing'].includes(order.status)&&<div className="notice" style={{marginBottom:20}}>Bu siparişin ödemesi tamamlanmış. İptal etmeden önce ödeme iadesi tamamlanmalıdır.</div>}
 <div className="form-card" style={{marginBottom:20}}><div className="section-head"><div><h2>Kargo ve Takip</h2><p className="muted">Kargo firmasını ve takip bilgilerini müşteriye gösterir.</p></div><button className="button" disabled={saving||order.status==='cancelled'||order.status==='delivered'} onClick={saveShipping}>Kargo Bilgisini Kaydet</button></div><div className="form-grid"><label>Kargo Firması<input value={shipping.shipping_carrier} onChange={e=>setShipping({...shipping,shipping_carrier:e.target.value})} placeholder="Örn. Yurtiçi Kargo"/></label><label>Takip Numarası<input value={shipping.tracking_number} onChange={e=>setShipping({...shipping,tracking_number:e.target.value})} placeholder="Takip numarası"/></label><label className="full">Takip Bağlantısı<input value={shipping.tracking_url} onChange={e=>setShipping({...shipping,tracking_url:e.target.value})} placeholder="https://..."/></label></div>{order.shipped_at&&<small className="muted">Kargoya veriliş: {new Date(order.shipped_at).toLocaleString('tr-TR')}</small>}</div>
 <div className="table-wrap"><table><thead><tr><th>Ürün</th><th>SKU</th><th>Adet</th><th>Birim Fiyat</th><th>Tutar</th></tr></thead><tbody>{order.order_items?.map(i=><tr key={i.id}><td>{i.product_name}</td><td>{i.sku||'—'}</td><td>{i.quantity}</td><td>{money(i.unit_price)}</td><td>{money(i.line_total)}</td></tr>)}{!order.order_items?.length&&<tr><td colSpan={5}>Sipariş kalemi bulunamadı.</td></tr>}</tbody></table></div>
 {order.status==='cancelled'&&<div className="notice">Bu sipariş iptal edildi. Ürün stokları yalnızca bir kez geri yüklenir ve sipariş tekrar aktif duruma alınamaz.</div>}{order.status==='delivered'&&<div className="notice">Bu sipariş teslim edildi. Sipariş durumu artık değiştirilemez.</div>}</>;
}
