'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { supabase } from '@/lib/supabase';
const money=(v:number)=>Number(v).toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
const statusLabels:Record<string,string>={new:'Yeni',confirmed:'Onaylandı',preparing:'Hazırlanıyor',shipped:'Kargolandı',delivered:'Teslim Edildi',cancelled:'İptal Edildi'};
const nextStatuses:Record<string,string[]>={new:['confirmed','preparing','cancelled'],confirmed:['preparing','cancelled'],preparing:['shipped','cancelled'],shipped:['delivered'],delivered:[],cancelled:[]};
export default function OrderDetail(){
 const {id}=useParams<{id:string}>(); const [order,setOrder]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
 const [shipping,setShipping]=useState({shipping_carrier:'',tracking_number:'',tracking_url:''});
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from('orders').select('*,customers(first_name,last_name,email,phone),addresses(title,full_name,phone,city,district,address_line,postal_code),order_items(id,product_name,sku,quantity,unit_price,line_total)').eq('id',id).single();if(error)setError(error.message);else {setOrder(data);setShipping({shipping_carrier:data.shipping_carrier||'',tracking_number:data.tracking_number||'',tracking_url:data.tracking_url||''});}setLoading(false)};
 useEffect(()=>{load()},[id]);
 const updateStatus=async(status:string)=>{if(status===order?.status)return;if(status==='cancelled'&&!confirm('Sipariş iptal edilsin ve ürünler stoğa geri eklensin mi?'))return;setSaving(true);setError('');const {error}=await supabase.rpc('admin_update_order_status',{p_order_id:id,p_new_status:status});if(error)setError(error.message);else await load();setSaving(false)};
 const saveShipping=async()=>{setSaving(true);setError('');const payload={shipping_carrier:shipping.shipping_carrier.trim()||null,tracking_number:shipping.tracking_number.trim()||null,tracking_url:shipping.tracking_url.trim()||null,shipped_at:order.status==='shipped'?(order.shipped_at||new Date().toISOString()):order.shipped_at};const {error}=await supabase.from('orders').update(payload).eq('id',id);if(error)setError(error.message);else await load();setSaving(false)};
 if(loading)return <p>Yükleniyor…</p>; if(!order)return <div className="error">{error||'Sipariş bulunamadı.'}</div>;
 const allowed=nextStatuses[order.status]||[];
 return <><div className="section-head"><div><h1>{order.order_number}</h1><p className="muted">Sipariş detayı ve operasyon yönetimi</p></div><select disabled={saving||allowed.length===0} value={order.status} onChange={e=>updateStatus(e.target.value)}><option value={order.status}>{statusLabels[order.status]||order.status}</option>{allowed.map(v=><option key={v} value={v}>{statusLabels[v]||v}</option>)}</select></div>{error&&<div className="error">{error}</div>}
 <div className="stats"><div className="card"><b>Müşteri</b><p>{order.customers?`${order.customers.first_name} ${order.customers.last_name}`:'—'}</p><small>{order.customers?.email||''}<br/>{order.customers?.phone||''}</small></div><div className="card"><b>Teslimat Adresi</b><p>{order.addresses?.full_name||'—'}</p><small>{[order.addresses?.address_line,order.addresses?.district,order.addresses?.city].filter(Boolean).join(' / ')}</small></div><div className="card"><b>Toplam</b><p>{money(order.total_amount)}</p><small>Ödeme: {order.payment_status}</small></div></div>
 <div className="form-card" style={{marginBottom:20}}><div className="section-head"><div><h2>Kargo ve Takip</h2><p className="muted">Kargo firmasını ve takip bilgilerini müşteriye gösterir.</p></div><button className="button" disabled={saving||order.status==='cancelled'||order.status==='delivered'} onClick={saveShipping}>Kargo Bilgisini Kaydet</button></div><div className="form-grid"><label>Kargo Firması<input value={shipping.shipping_carrier} onChange={e=>setShipping({...shipping,shipping_carrier:e.target.value})} placeholder="Örn. Yurtiçi Kargo"/></label><label>Takip Numarası<input value={shipping.tracking_number} onChange={e=>setShipping({...shipping,tracking_number:e.target.value})} placeholder="Takip numarası"/></label><label className="full">Takip Bağlantısı<input value={shipping.tracking_url} onChange={e=>setShipping({...shipping,tracking_url:e.target.value})} placeholder="https://..."/></label></div>{order.shipped_at&&<small className="muted">Kargoya veriliş: {new Date(order.shipped_at).toLocaleString('tr-TR')}</small>}</div>
 <div className="table-wrap"><table><thead><tr><th>Ürün</th><th>SKU</th><th>Adet</th><th>Birim Fiyat</th><th>Tutar</th></tr></thead><tbody>{order.order_items?.map((i:any)=><tr key={i.id}><td>{i.product_name}</td><td>{i.sku||'—'}</td><td>{i.quantity}</td><td>{money(i.unit_price)}</td><td>{money(i.line_total)}</td></tr>)}</tbody></table></div>
 {order.status==='cancelled'&&<div className="notice">Bu sipariş iptal edildi. Ürün stokları yalnızca bir kez geri yüklenir ve sipariş tekrar aktif duruma alınamaz.</div>}{order.status==='delivered'&&<div className="notice">Bu sipariş teslim edildi. Sipariş durumu artık değiştirilemez.</div>}</>;
}
