'use client';
import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Row={id:string;name:string;sku:string|null;price:number|string;stock_quantity:number;is_active:boolean;category_id:string|null;brand_id:string|null};
type Named={id:string;name:string};
export default function Products(){
 const [rows,setRows]=useState<Row[]>([]);const [cats,setCats]=useState<Record<string,string>>({});const [brands,setBrands]=useState<Record<string,string>>({});const [msg,setMsg]=useState('');const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);const [{data,error},{data:c},{data:b}]=await Promise.all([supabase.from('products').select('id,name,sku,price,stock_quantity,is_active,category_id,brand_id').order('created_at',{ascending:false}),supabase.from('categories').select('id,name'),supabase.from('brands').select('id,name')]);if(error)setMsg(error.message);setRows((data??[]) as Row[]);setCats(Object.fromEntries(((c??[]) as Named[]).map(x=>[x.id,x.name])));setBrands(Object.fromEntries(((b??[]) as Named[]).map(x=>[x.id,x.name])));setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function remove(row:Row){if(!confirm(`“${row.name}” ürünü silinsin mi?`))return;setMsg('');const {data:imgs}=await supabase.from('product_images').select('id,image_url').eq('product_id',row.id);if(imgs?.length){const marker='/storage/v1/object/public/product-images/';const paths=imgs.map(x=>{const pos=x.image_url.indexOf(marker);return pos>=0?decodeURIComponent(x.image_url.slice(pos+marker.length)):null}).filter(Boolean) as string[];if(paths.length)await supabase.storage.from('product-images').remove(paths);const {error:ie}=await supabase.from('product_images').delete().eq('product_id',row.id);if(ie){setMsg('Görseller silinemedi: '+ie.message);return}}
 const {error}=await supabase.from('products').delete().eq('id',row.id);if(error){setMsg('Ürün silinemedi: '+error.message);return}setMsg('Ürün silindi.');await load()}
 return <><div className="page-head"><div><h1>Ürünler</h1><p className="muted">Ürün, fiyat ve stok kayıtlarını yönetin.</p></div><a className="button" href="/admin/products/new">+ Yeni Ürün</a></div>{msg&&<div className={msg==='Ürün silindi.'?'ok':'error'}>{msg}</div>}{loading?<div className="card">Yükleniyor…</div>:<div className="table-wrap"><table className="table"><thead><tr><th>Ürün</th><th>SKU</th><th>Marka</th><th>Kategori</th><th>Fiyat</th><th>Stok</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.sku||'—'}</td><td>{x.brand_id?brands[x.brand_id]||'—':'—'}</td><td>{x.category_id?cats[x.category_id]||'—':'—'}</td><td>{Number(x.price).toLocaleString('tr-TR',{minimumFractionDigits:2})} ₺</td><td>{x.stock_quantity}</td><td><span className={x.is_active?'badge active':'badge'}>{x.is_active?'Aktif':'Pasif'}</span></td><td><div className="row-actions"><a href={`/admin/products/${x.id}/edit`}>Düzenle</a><button onClick={()=>remove(x)}>Sil</button></div></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty">Henüz ürün yok.</div>}</div>}</>}
