'use client';
import { FormEvent,useEffect,useState } from 'react';import { supabase } from '@/lib/supabase';
type Coupon={id:string;code:string;description:string|null;discount_type:string;discount_value:number;min_subtotal:number;usage_limit:number|null;is_active:boolean};
type Campaign={id:string;title:string;slug:string;description:string|null;badge_text:string|null;is_active:boolean};
export default function PromotionsPage(){const [coupons,setCoupons]=useState<Coupon[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [msg,setMsg]=useState('');async function load(){const [{data:c},{data:p}]=await Promise.all([supabase.from('coupons').select('id,code,description,discount_type,discount_value,min_subtotal,usage_limit,is_active').order('created_at',{ascending:false}),supabase.from('campaigns').select('id,title,slug,description,badge_text,is_active').order('created_at',{ascending:false})]);setCoupons((c||[]) as Coupon[]);setCampaigns((p||[]) as Campaign[])}useEffect(()=>{load()},[]);
 async function addCoupon(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.from('coupons').insert({code:String(f.get('code')).trim().toUpperCase(),description:String(f.get('description')||''),discount_type:String(f.get('type')),discount_value:Number(f.get('value')),min_subtotal:Number(f.get('min')||0),usage_limit:f.get('limit')?Number(f.get('limit')):null,is_active:true});setMsg(error?error.message:'Kupon eklendi');if(!error){e.currentTarget.reset();load()}}
 async function addCampaign(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const title=String(f.get('title'));const slug=title.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const {error}=await supabase.from('campaigns').insert({title,slug,description:String(f.get('description')||''),badge_text:String(f.get('badge')||''),is_active:true});setMsg(error?error.message:'Kampanya eklendi');if(!error){e.currentTarget.reset();load()}}
 async function toggle(table:'coupons'|'campaigns',id:string,current:boolean){await supabase.from(table).update({is_active:!current}).eq('id',id);load()}
 return <div><div className="page-head"><div><h1>Kampanya & Kuponlar</h1><p className="muted">Promosyonları ve sepet indirim kodlarını yönetin.</p></div></div>{msg&&<div className="notice">{msg}</div>}<div className="promo-admin-grid"><section className="form-card"><h2>Yeni Kupon</h2><form onSubmit={addCoupon} className="form-grid two"><label>Kod<input required name="code" placeholder="VIVA10"/></label><label>İndirim türü<select name="type"><option value="percentage">Yüzde</option><option value="fixed">Sabit TL</option></select></label><label>İndirim değeri<input required min="0.01" step="0.01" type="number" name="value"/></label><label>Min. sepet<input min="0" step="0.01" type="number" name="min" defaultValue="0"/></label><label>Kullanım limiti<input min="1" type="number" name="limit"/></label><label className="full">Açıklama<input name="description"/></label><button className="button" type="submit">Kupon Ekle</button></form><div className="mini-list">{coupons.map(x=><div key={x.id}><span><b>{x.code}</b> · {x.discount_type==='percentage'?`%${x.discount_value}`:`${x.discount_value} TL`}</span><button className="link-button" onClick={()=>toggle('coupons',x.id,x.is_active)}>{x.is_active?'Pasif Yap':'Aktif Yap'}</button></div>)}</div></section><section className="form-card"><h2>Yeni Kampanya</h2><form onSubmit={addCampaign} className="form-grid"><label>Başlık<input required name="title"/></label><label>Rozet<input name="badge" placeholder="Yeni / Fırsat"/></label><label>Açıklama<textarea name="description" rows={3}/></label><button className="button" type="submit">Kampanya Ekle</button></form><div className="mini-list">{campaigns.map(x=><div key={x.id}><span><b>{x.title}</b>{x.badge_text?` · ${x.badge_text}`:''}</span><button className="link-button" onClick={()=>toggle('campaigns',x.id,x.is_active)}>{x.is_active?'Pasif Yap':'Aktif Yap'}</button></div>)}</div></section></div></div>}
