'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import AdminFeedback from './AdminFeedback';

const orderLabels:Record<string,string>={new:'Yeni',confirmed:'Onaylandı',preparing:'Hazırlanıyor',shipped:'Kargolandı',delivered:'Teslim Edildi',cancelled:'İptal Edildi'};
const money=(value:number)=>Number(value||0).toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
type Product={id:string;name:string;sku:string|null;stock_quantity:number;is_active:boolean};
type Customer={first_name:string|null;last_name:string|null};
type Order={id:string;order_number:string;status:string;payment_status:string;total_amount:number;created_at:string;customers:Customer[]|null};

export default function Admin(){
 const [products,setProducts]=useState<Product[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [categoryCount,setCategoryCount]=useState<number|null>(null);const [brandCount,setBrandCount]=useState<number|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let active=true;(async()=>{setLoading(true);setError('');try{const [productResult,orderResult,categoryResult,brandResult]=await Promise.all([supabase.from('products').select('id,name,sku,stock_quantity,is_active').order('stock_quantity',{ascending:true}),supabase.from('orders').select('id,order_number,status,payment_status,total_amount,created_at,customers(first_name,last_name)').order('created_at',{ascending:false}).limit(5),supabase.from('categories').select('*',{count:'exact',head:true}),supabase.from('brands').select('*',{count:'exact',head:true})]);if(!active)return;const firstError=productResult.error||orderResult.error||categoryResult.error||brandResult.error;if(firstError){setError('Dashboard verileri yüklenemedi. Lütfen oturumunuzu ve bağlantınızı kontrol edin.');return}setProducts((productResult.data??[]) as Product[]);setOrders((orderResult.data??[]) as Order[]);setCategoryCount(categoryResult.count??0);setBrandCount(brandResult.count??0)}catch{if(active)setError('Dashboard yüklenirken beklenmeyen bir hata oluştu.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const activeProducts=products.filter(product=>product.is_active).length;const lowStock=products.filter(product=>product.is_active&&product.stock_quantity<=5);const pendingOrders=orders.filter(order=>['new','confirmed','preparing'].includes(order.status)).length;
 return <><div className="page-head"><div><h1>Dashboard</h1><p className="muted">Mağaza operasyonlarının güncel özeti.</p></div><div className="admin-quick-actions"><Link className="button" href="/admin/products/new">+ Yeni Ürün</Link><Link className="button secondary" href="/admin/orders">Siparişleri Aç</Link></div></div>{error&&<AdminFeedback tone="error" message={error}/>}{loading?<div className="card" role="status">Dashboard yükleniyor…</div>:!error?<><div className="dashboard-stats"><Link href="/admin/products" className="card"><b>{products.length}</b><span>Toplam ürün</span><small>{activeProducts} aktif</small></Link><Link href="/admin/orders" className="card"><b>{pendingOrders}</b><span>İşlem bekleyen sipariş</span><small>Yeni, onaylanan ve hazırlanan</small></Link><Link href="/admin/products" className="card"><b>{lowStock.length}</b><span>Kritik veya tükenen stok</span><small>5 adet ve altı</small></Link><Link href="/admin/categories" className="card"><b>{categoryCount??'—'}</b><span>Kategori</span><small>{brandCount??'—'} marka</small></Link></div><div className="dashboard-grid"><section className="form-card"><div className="section-row"><div><h2>Son Siparişler</h2><p className="muted">En yeni 5 sipariş</p></div><Link className="link-button" href="/admin/orders">Tümünü Gör</Link></div>{orders.length?<div className="dashboard-order-list">{orders.map(order=>{const customer=order.customers?.[0];const customerName=customer?`${customer.first_name||''} ${customer.last_name||''}`.trim():'';return <Link key={order.id} href={`/admin/orders/${order.id}`}><div><b>{order.order_number}</b><small>{customerName||'Müşteri bilgisi yok'} · {new Date(order.created_at).toLocaleString('tr-TR')}</small></div><span className={`order-status ${order.status}`}>{orderLabels[order.status]||order.status}</span><strong>{money(order.total_amount)}</strong></Link>})}</div>:<div className="empty">Henüz sipariş yok.</div>}</section><section className="form-card"><div className="section-row"><div><h2>Stok Uyarıları</h2><p className="muted">Öncelikli ürünler</p></div><Link className="link-button" href="/admin/products">Ürünlere Git</Link></div>{lowStock.length?<div className="dashboard-stock-list">{lowStock.slice(0,6).map(product=><Link key={product.id} href={`/admin/products/${product.id}/edit`}><div><b>{product.name}</b><small>{product.sku||'SKU yok'}</small></div><span className={product.stock_quantity<=0?'badge danger':'badge warning'}>{product.stock_quantity<=0?'Tükendi':`${product.stock_quantity} adet`}</span></Link>)}</div>:<div className="ok">Aktif ürünlerde kritik stok bulunmuyor.</div>}</section></div></>:null}</>;
}
