import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import { StoreHeader } from '@/components/StoreHeader';
import { AddToCartButton } from '@/components/AddToCartButton';
import { createPublicServerClient } from '@/lib/supabase-public-server';
import styles from './product.module.css';

type Product={id:string;name:string;slug:string;description:string|null;price:number|string;compare_at_price:number|string|null;stock_quantity:number;seo_title:string|null;seo_description:string|null;sku:string|null;barcode:string|null;brands:{name:string}|null;categories:{name:string}|null;product_images:{id:string;image_url:string;alt_text:string|null;sort_order:number;is_primary:boolean}[]|null};
async function getProduct(slug:string){const supabase=createPublicServerClient();const {data}=await supabase.from('products').select('id,name,slug,description,price,compare_at_price,stock_quantity,seo_title,seo_description,sku,barcode,brands(name),categories(name),product_images(id,image_url,alt_text,sort_order,is_primary)').eq('slug',slug).eq('is_active',true).maybeSingle();return data as unknown as Product|null}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=await getProduct(slug);if(!p)return{title:'Ürün Bulunamadı | Vivatech',robots:{index:false,follow:false}};const images=[...(p.product_images??[])].sort((a,b)=>a.sort_order-b.sort_order);return{title:p.seo_title||`${p.name} | Vivatech`,description:p.seo_description||p.description?.slice(0,160)||`${p.name} Vivatech güvenlik sistemleri mağazasında.`,openGraph:{title:p.seo_title||p.name,description:p.seo_description||p.description?.slice(0,160)||p.name,images:images[0]?.image_url?[{url:images[0].image_url,alt:images[0].alt_text||p.name}]:[]}}}
const money=(v:number|string)=>Number(v).toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const product=await getProduct(slug);if(!product)return <main className="store"><StoreHeader/><div className="empty">Ürün bulunamadı.<br/><Link className="back-link" href="/products">Ürünlere dön</Link></div></main>;
 const images=[...(product.product_images??[])].sort((a,b)=>a.sort_order-b.sort_order);const primary=images.find(x=>x.is_primary)||images[0];const saving=product.compare_at_price&&Number(product.compare_at_price)>Number(product.price)?Math.round((1-Number(product.price)/Number(product.compare_at_price))*100):0;
 return <main className="store"><StoreHeader/><div className={styles.breadcrumb}><Link href="/">Ana Sayfa</Link><span>›</span><Link href="/products">Ürünler</Link>{product.categories?.name&&<><span>›</span><span>{product.categories.name}</span></>}</div>
 <section className={styles.detail}><div className={styles.gallery}>{primary?<div className={styles.mainImage}><Image src={primary.image_url} alt={primary.alt_text??product.name} width={1000} height={1000} priority/>{saving?<span className={styles.discount}>%{saving} İndirim</span>:null}</div>:<div className="product-media large">VIVATECH</div>}{images.length>1&&<div className={styles.thumbs}>{images.map(img=><div key={img.id} className={styles.thumb}><Image src={img.image_url} alt={img.alt_text??product.name} width={220} height={220}/></div>)}</div>}</div>
 <div className={styles.info}><span className="eyebrow">{product.brands?.name||'VIVATECH'}</span><h1>{product.name}</h1><div className={styles.code}>{product.sku&&<span>Ürün Kodu: <b>{product.sku}</b></span>}{product.barcode&&<span>Barkod: {product.barcode}</span>}</div><div className={styles.price}><strong>{money(product.price)}</strong>{product.compare_at_price&&<del>{money(product.compare_at_price)}</del>}{saving?<span>%{saving} avantaj</span>:null}</div><div className={product.stock_quantity>0?styles.stock:styles.noStock}>{product.stock_quantity>0?`✓ Stokta • ${product.stock_quantity} adet hazır`:'Stokta yok'}</div>
 <AddToCartButton product={{id:product.id,name:product.name,slug:product.slug,price:Number(product.price),stock_quantity:product.stock_quantity,image_url:primary?.image_url}}/>
 <div className={styles.benefits}><div><b>🚚 Hızlı Gönderim</b><span>Siparişiniz özenle hazırlanır.</span></div><div><b>🛡️ 2 Yıl Garanti</b><span>Satış sonrası destek yanınızda.</span></div><div><b>🔒 Güvenli Alışveriş</b><span>Sipariş ve stok altyapısı güvenlidir.</span></div></div>
 <div className={styles.miniHelp}><b>Bu ürün size uygun mu?</b><span>4G, solar ve kamera özelliklerini ihtiyacınıza göre karşılaştırabilirsiniz.</span></div></div></section>
 <section className={styles.description}><div><span className="eyebrow">ÜRÜN BİLGİLERİ</span><h2>Ürün Açıklaması</h2></div><p>{product.description||'Ürün açıklaması henüz eklenmedi.'}</p></section></main>}
