import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import { StoreHeader } from '@/components/StoreHeader';
import { AddToCartButton } from '@/components/AddToCartButton';
import { createPublicServerClient } from '@/lib/supabase-public-server';

type Product={id:string;name:string;slug:string;description:string|null;price:number|string;compare_at_price:number|string|null;stock_quantity:number;seo_title:string|null;seo_description:string|null;product_images:{id:string;image_url:string;alt_text:string|null;sort_order:number;is_primary:boolean}[]|null};
async function getProduct(slug:string){const supabase=createPublicServerClient();const {data}=await supabase.from('products').select('id,name,slug,description,price,compare_at_price,stock_quantity,seo_title,seo_description,product_images(id,image_url,alt_text,sort_order,is_primary)').eq('slug',slug).eq('is_active',true).maybeSingle();return data as Product|null}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=await getProduct(slug);if(!p)return{title:'Ürün Bulunamadı | Vivatech',robots:{index:false,follow:false}};const images=[...(p.product_images??[])].sort((a,b)=>a.sort_order-b.sort_order);return{title:p.seo_title||`${p.name} | Vivatech`,description:p.seo_description||p.description?.slice(0,160)||`${p.name} Vivatech güvenlik sistemleri mağazasında.`,openGraph:{title:p.seo_title||p.name,description:p.seo_description||p.description?.slice(0,160)||p.name,images:images[0]?.image_url?[{url:images[0].image_url,alt:images[0].alt_text||p.name}]:[]}}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const product=await getProduct(slug);if(!product)return <main className="store"><StoreHeader/><div className="empty">Ürün bulunamadı.<br/><Link className="back-link" href="/products">Ürünlere dön</Link></div></main>;const images=[...(product.product_images??[])].sort((a,b)=>a.sort_order-b.sort_order);return <main className="store"><StoreHeader/><section className="product-detail"><div className="detail-gallery">{images.length?images.map(img=><Image key={img.id} src={img.image_url} alt={img.alt_text??product.name} width={900} height={900}/>):<div className="product-media large">VIVATECH</div>}</div><div className="detail-info"><span className="eyebrow">VIVATECH</span><h1>{product.name}</h1><div className="detail-price"><strong>{Number(product.price).toLocaleString('tr-TR',{style:'currency',currency:'TRY'})}</strong>{product.compare_at_price&&<del>{Number(product.compare_at_price).toLocaleString('tr-TR',{style:'currency',currency:'TRY'})}</del>}</div><div className={product.stock_quantity>0?'stock-ok':'stock-no'}>{product.stock_quantity>0?`Stokta ${product.stock_quantity} adet`:'Stokta yok'}</div><AddToCartButton product={{id:product.id,name:product.name,slug:product.slug,price:Number(product.price),stock_quantity:product.stock_quantity,image_url:images[0]?.image_url}}/><div className="description"><h2>Ürün Açıklaması</h2><p>{product.description||'Ürün açıklaması henüz eklenmedi.'}</p></div></div></section></main>}
