'use client';
import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Block={id:string;title:string;body:string|null;badge_text:string|null;link_url:string|null;button_text:string|null;placement:string;sort_order:number;is_active:boolean};
export default function ContentPage(){const [items,setItems]=useState<Block[]>([]);const [msg,setMsg]=useState('');
 async function load(){const {data,error}=await supabase.from('content_blocks').select('*').order('placement').order('sort_order');if(error)setMsg(error.message);setItems((data||[]) as Block[])}useEffect(()=>{load()},[]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.from('content_blocks').insert({title:String(f.get('title')),body:String(f.get('body')||''),badge_text:String(f.get('badge_text')||'')||null,link_url:String(f.get('link_url')||'')||null,button_text:String(f.get('button_text')||'')||null,placement:String(f.get('placement')),sort_order:Number(f.get('sort_order')||0),is_active:true});setMsg(error?error.message:'İçerik eklendi');if(!error){e.currentTarget.reset();load()}}
 async function toggle(id:string,current:boolean){const {error}=await supabase.from('content_blocks').update({is_active:!current}).eq('id',id);setMsg(error?error.message:'İçerik güncellendi');if(!error)load()}
 async function remove(id:string){if(!confirm('İçerik silinsin mi?'))return;const {error}=await supabase.from('content_blocks').delete().eq('id',id);setMsg(error?error.message:'İçerik silindi');if(!error)load()}
 return <div><div className="page-head"><div><h1>İçerik Yönetimi</h1><p className="muted">Ana sayfada gösterilecek bilgi, avantaj ve kampanya bloklarını yönetin.</p></div></div>{msg&&<div className="notice">{msg}</div>}<div className="content-admin-grid"><section className="form-card"><h2>Yeni İçerik</h2><form onSubmit={add} className="form-grid two"><label className="full">Başlık<input required name="title"/></label><label className="full">Metin<textarea name="body" rows={5}/></label><label>Rozet<input name="badge_text" placeholder="Fırsat / Yeni"/></label><label>Konum<select name="placement"><option value="home_after_hero">Hero Altı</option><option value="home_after_categories">Kategori Altı</option><option value="home_after_products">Ürünler Altı</option><option value="home_before_footer">Footer Üstü</option></select></label><label>Buton yazısı<input name="button_text"/></label><label>Bağlantı<input name="link_url" placeholder="/products"/></label><label>Sıra<input type="number" name="sort_order" defaultValue="0"/></label><button className="button" type="submit">İçerik Ekle</button></form></section><section className="form-card"><h2>İçerik Listesi</h2><div className="admin-card-list">{items.length===0?<div className="empty">Henüz içerik yok.</div>:items.map(x=><div className="admin-content-card" key={x.id}><div><b>{x.title}</b><small>{x.placement} · Sıra {x.sort_order}</small><small>{x.is_active?'Aktif':'Pasif'}</small></div><div className="admin-content-actions"><button className="link-button" onClick={()=>toggle(x.id,x.is_active)}>{x.is_active?'Pasif Yap':'Aktif Yap'}</button><button className="link-button danger" onClick={()=>remove(x.id)}>Sil</button></div></div>)}</div></section></div></div>}
